### ISSUE TITLE
Sorting is not working

### ISSUE THREAD

**Issue by vivgui** [d4rkr00t/css-comb-atom#11]
I just installed this plugin and added a .csscomb.json file with my config but everything works except for the property sorting. This is on Atom 1.0.15.

**Comment by d4rkr00t** [comment]
Hi, could you please look at the console cmd+alt+i on mac are there any errors from css-comb-atom? 

Also you can try to open "Key Binding Resolver" by pressing cmd+. and after you press ctrl+alt+c you'll see if css comb key binding matched. 

And also, you can open command palette (cmd+shift+p) and run css comb from there.

If it doesn't help, write here again and i'll take a look after vacation :)

**Comment by d4rkr00t** [comment]
Hi! Are you still having this issue? Or can i close this one?

**Comment by vivgui** [comment]
Sorry for the delay, the notification went to my old email. 

I don't see any errors in the console but I checked the Key Binding and is not associated with csscomb, also I tried running it from the command palette but the sorting still doesnt work.

**Comment by d4rkr00t** [comment]
Hm, I don't even know why it won't work. It has to. :) 

So. Few more questions:
1. What type of file you are trying to sort? Is it css? 
2. Did you save file or you've just created a tab in atom and try to sort there?
3. What OS do you use Mac, Linux or Windows? 
4. Could you give me your .csscomb.json and file your are sorting?
5. Could you give me screenshot of your atom css-comb settings?

**Comment by vivgui** [comment]
1 - I'm trying to sort a SASS file. 
2 - I'm saving the file. 
3 - I'm using Mac.
4 - Here is my css-comb.json and the file I'm working on. https://www.dropbox.com/sh/9phcxr62b2w7821/AAAo3Dih81uNzyAvrHxHItbQa?dl=0
Btw, I'm using .css-comb.json, I removed the button to be able to upload it. 
5 - I'm attaching screenshot of my settings here. 

![screen shot 2015-10-15 at 9 53 20 am](https://cloud.githubusercontent.com/assets/7389358/10515697/a4e55c6a-7322-11e5-906c-d2562acc3ef8.png)

**Comment by d4rkr00t** [comment]
Oh, ok, I understood why sorting isn't working. It's because your .csscomb.json doesn't have any sort-order rules in it. 

To fix this you can just use one of the [predefined configs](https://github.com/csscomb/csscomb.js/blob/master/config/) or you can read a documentation how to configure csscomb sort-order and other options here — https://github.com/csscomb/csscomb.js/blob/master/doc/configuration.md 

Also you can "disable config searching" in package settings and sorting will work with csscomb default config.
