### ISSUE TITLE
Problems with colons

### ISSUE THREAD

**Issue by Gruntfuggly** [d4rkr00t/css-comb-atom#36]
If I use something like:

```
div:first-child
{
    margin-right: 1em;
}

div
{
    width: 50%;
}
```

css-comb indents the second block (because of the colon in div:first-child) so it becomes:

```
div: first-child
{
    margin-right: 1em;
}

    div
    {
        width: 50%;
    }
```

It also puts a space after the colon in div:first-child.

Is there any way around this?

**Comment by d4rkr00t** [comment]
Hi, thank  you for report. But could you provide some more information?
- Your csscomb config
- File extension (because csscomb uses file extension to determine appropriate syntax)
- Do you run whole file through csscomb or only selection?

Also you can try to run csscomb from terminal.

```
csscomb -c path_to_config filename
```

And if you can reproduce it in your terminal (I strongly believe you will reproduce it) it means it's an issue with csscomb itself not with plugin. Because this plugin only runs csscomb under the hood.

**Comment by Gruntfuggly** [comment]
> On 1 Jun 2016, at 17:04, Stanislav Sysoev notifications@github.com wrote:
> 
> Hi, thank you for report. But could you provide some more information?
> 
>   • Your csscomb config
>   • File extension (because csscomb uses file extension to determine appropriate syntax)
>   • Do you run whole file through csscomb or only selection?
> Also you can try to run csscomb from terminal.
> 
> csscomb -c path_to_config filename
> 
> And if you can reproduce it in your terminal (I strongly believe you will reproduce it) it means it's an issue with csscomb itself not with plugin. Because this plugin only runs csscomb under the hood.

Hi there

I am using the predefined configuration (csscomb), on a .less file. I run it on file save, so it processes the whole file.

You’re correct that it does the same thing from the terminal.

I’ll raise an issue with csscomb.

Thanks for your quick response.

Regards,
Nigel

**Comment by d4rkr00t** [comment]
Ok. I hope they'll fix it soon :), and thank you for the report again.
