### ISSUE TITLE
Add all options to settings

### ISSUE THREAD

**Issue by lukasoppermann** [d4rkr00t/css-comb-atom#5]
Hey,

cloud you make it possible to adjust all options in the settings screen?
Maybe you could add all options as checkboxes or input fields and a textarea for the sort-order? 

Also maybe you could use a placeholder in the input fields to hint what kind of input is selected.

**Comment by d4rkr00t** [comment]
Hi,

I don't think it's a good idea, because there are about 25 options for csscomb and they have about 4 or 5 different types. Main idea behind this plugin is to get config from your current project directory so you can work in different code style environments easier. 

If you want to setup all options in one place you can create file ~/.csscomb.json define it as custom config and disable config search.

**Comment by lukasoppermann** [comment]
Ahh, okay, I did not know that it will read the `~/.csscomb.json` thanks

// EDIT:
actually, I created `~/.csscomb.json` and added `~/.csscomb.json` to the custom input, but it only uses the predefined one.

**Comment by d4rkr00t** [comment]
Hm it looks like a bug, i'll have a look on it. Thanks!

**Comment by lukasoppermann** [comment]
Thank you for taking a look, if you need any more info, just tell me what you need.

**Comment by d4rkr00t** [comment]
What OS do you use?

**Comment by lukasoppermann** [comment]
Mac osx mavericks

Stanislav Sysoev notifications@github.com schrieb am Mi., 11. März 2015
13:38:
